"""add column description

Revision ID: 21b628ec8d7a
Revises: 10eede59829f
Create Date: 2012-11-07 23:22:29.275084

"""

# revision identifiers, used by Alembic.
revision = '21b628ec8d7a'
down_revision = '10eede59829f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(length=1024), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    ### end Alembic commands ###
