#!/usr/bin/env python
# coding: utf-8
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), 'paver-minilib.zip'))

from paver.easy import *


@task
def hello():
    print 'hello'


if __name__ == '__main__':
    tasks.main(['-f'] + sys.argv)

# eof
